### ISSUE TITLE
IIASA 2023 work

### ISSUE THREAD

**Issue by Nowosad** [r-spatialecology/landscapemetrics#302]
Improvements (see https://github.com/Nowosad/lsm2023improvements):

- [x] create an "extras" mechanism for `calculate_lsm()` (and other related functions) to speed-up calculations of many metrics at the same time (see https://github.com/r-spatialecology/landscapemetrics/issues/154 and https://github.com/r-spatialecology/landscapemetrics/issues/199) [jn: added to the commoncalc branch]
- [x] test if `as.int()` gives any speed improvements [no visible improvements or deterioration in terms of speed; however the internal matrix object should be smaller, and thus I would suggest doing it]
- [x] clean Rcpp code [jn: added some const and &]
- [x] check if using terra::focalCpp would be beneficial (see https://github.com/r-spatialecology/landscapemetrics/issues/224) [jn: in short, no. It only makes practical sense if the metrics are calculated using a C++ code]
- [x] try the `new_tibble(list(` approach [jn: the performance gain is ~20ms; rewritting is probably not worth it] [jn: later, we discovered that actually this was very important to improve window_lsm speed]
- [x] `rcpp_get_coocurrence_matrix_single` is used directly and indirectly by ~10 metrics -- there should be a way to improving this part
- [x] confirm that everything works as expected
- [x] clean and document the new changes (version 2.1) [jn: see <https://github.com/r-spatialecology/landscapemetrics/blob/commoncalcs/NEWS.md#landscapemetrics-210>]

Bug fixes:

- [x] https://github.com/r-spatialecology/landscapemetrics/issues/300
- [x] https://github.com/r-spatialecology/landscapemetrics/issues/215
- [x] https://github.com/r-spatialecology/landscapemetrics/issues/301

Questions to answer:

- [x] https://github.com/r-spatialecology/landscapemetrics/issues/298

Misc:

- [x] https://github.com/r-spatialecology/landscapemetrics/issues/260
- [x] update the FRAGSTATS tests -- https://github.com/r-spatialecology/landscapemetrics/issues/294
- [x] rerender the book chapter to check 3.1 version
- [ ] create a data base of metrics properties

**Comment by kadyb** [comment]
>  test if as.int() gives any speed improvements

The object is R matrix/array or SpatRaster? If SpatRaster, then the object is held in memory as float.

**Comment by Nowosad** [comment]
@kadyb yep -- we have a SpatRaster, but then we convert it into a matrix (`as.matrix(x, wide = TRUE)`). The resulting matrix is either double (when as.int is not used previously) or integer (when as.int is applied beforehand).

**Comment by mhesselbarth** [comment]
I think once your merged the PR with the common calculates, we can also close this issue again?

**Comment by Nowosad** [comment]
Yep -- I plan to work on the remaining points during the next week and then I will undraft the PR.

**Comment by Nowosad** [comment]
See https://jakubnowosad.com/lsm2023improvements/

**Comment by mhesselbarth** [comment]
PR is merged to main and commoncalcs deleted. Will update the CRAN version soon.
